// projects/frontend/src/schema/components/DriftPanel.svelte
<script lang="ts">
  interface Props {
    drift: DriftReport;
    ongoto: (id: string) => void;
  }
  let { drift, ongoto }: Props = $props();

  let open = $state(false);

  function goTo(id: string) {
    ongoto(id);
    open = false;
  }

  const cd = $derived(drift.constraintDrift);
</script>

{#if drift.totalIssues === 0}
  <button id="drift-btn" class="clean" title="No config drift">&#x2713;</button>
{:else}
  <button id="drift-btn" class="has-issues" onclick={() => (open = !open)} title="Config drift detected">
    &#x26A0; {drift.totalIssues}
  </button>

  <div id="drift-panel" class={open ? 'open' : ''}>
    <div id="drift-header">
      <h2>Config Drift</h2>
      <button id="drift-close" onclick={() => (open = false)}>&times;</button>
    </div>

    {#if drift.unassignedTables.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title amber">Unassigned Tables ({drift.unassignedTables.length})</h3>
        <p class="drift-section-desc">In database but not in any domain</p>
        {#each drift.unassignedTables as name (name)}
          <div class="drift-item clickable" onclick={() => goTo(name)} role="button" tabindex="0" onkeydown={(e) => { if (e.key === 'Enter') goTo(name); }}>
            {name}
          </div>
        {/each}
      </div>
    {/if}

    {#if drift.ghostTables.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title red">Ghost Tables ({drift.ghostTables.length})</h3>
        <p class="drift-section-desc">In config but not in database</p>
        {#each drift.ghostTables as name (name)}
          <div class="drift-item">{name}</div>
        {/each}
      </div>
    {/if}

    {#if drift.unmappedFkColumns.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title blue">Unmapped FK Columns ({drift.unmappedFkColumns.length})</h3>
        <p class="drift-section-desc">Look like FKs but have no mapping</p>
        {#each drift.unmappedFkColumns as { table, column } (`${table}.${column}`)}
          <div class="drift-item clickable" onclick={() => goTo(table)} role="button" tabindex="0" onkeydown={(e) => { if (e.key === 'Enter') goTo(table); }}>
            <span class="drift-table">{table}</span>.<span class="drift-col">{column}</span>
          </div>
        {/each}
      </div>
    {/if}

    {#if drift.invalidFkTargets.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title red">Invalid FK Targets ({drift.invalidFkTargets.length})</h3>
        <p class="drift-section-desc">FK mappings to non-existent tables</p>
        {#each drift.invalidFkTargets as { column, target } (column)}
          <div class="drift-item">
            {column} &rarr; <span class="drift-col">{target}</span>
          </div>
        {/each}
      </div>
    {/if}

    {#if cd && cd.missingDbConstraints.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title amber">Missing DB Constraints ({cd.missingDbConstraints.length})</h3>
        <p class="drift-section-desc">In config but no actual DB foreign key constraint</p>
        {#each cd.missingDbConstraints as { table, column, target } (`${table}.${column}`)}
          <div class="drift-item clickable" onclick={() => goTo(table)} role="button" tabindex="0" onkeydown={(e) => { if (e.key === 'Enter') goTo(table); }}>
            <span class="drift-table">{table}</span>.<span class="drift-col">{column}</span> &rarr; {target}
          </div>
        {/each}
      </div>
    {/if}

    {#if cd && cd.extraDbConstraints.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title blue">Extra DB Constraints ({cd.extraDbConstraints.length})</h3>
        <p class="drift-section-desc">DB has FK constraint but no config mapping</p>
        {#each cd.extraDbConstraints as { table, column, referencedTable } (`${table}.${column}`)}
          <div class="drift-item clickable" onclick={() => goTo(table)} role="button" tabindex="0" onkeydown={(e) => { if (e.key === 'Enter') goTo(table); }}>
            <span class="drift-table">{table}</span>.<span class="drift-col">{column}</span> &rarr; {referencedTable}
          </div>
        {/each}
      </div>
    {/if}

    {#if cd && cd.mismatchedFkTargets.length > 0}
      <div class="drift-section">
        <h3 class="drift-section-title red">Mismatched FK Targets ({cd.mismatchedFkTargets.length})</h3>
        <p class="drift-section-desc">Config and DB disagree on FK target table</p>
        {#each cd.mismatchedFkTargets as { table, column, configTarget, actualTarget } (`${table}.${column}`)}
          <div class="drift-item clickable" onclick={() => goTo(table)} role="button" tabindex="0" onkeydown={(e) => { if (e.key === 'Enter') goTo(table); }}>
            <span class="drift-table">{table}</span>.<span class="drift-col">{column}</span>: config &rarr; {configTarget}, DB &rarr; {actualTarget}
          </div>
        {/each}
      </div>
    {/if}
  </div>
{/if}

// projects/frontend/src/schema/components/DriftPanel.tsx
import { useState } from 'react';
import type { ReactNode } from 'react';

function DriftSection({ title, titleClass, description, children }: { title: string; titleClass: string; description: string; children: ReactNode }) {
  return (
    <div className="drift-section">
      <h3 className={`drift-section-title ${titleClass}`}>{title}</h3>
      <p className="drift-section-desc">{description}</p>
      {children}
    </div>
  );
}

export function DriftPanel({ drift, onGoTo }: { drift: DriftReport; onGoTo: (id: string) => void }) {
  const [open, setOpen] = useState(false);

  if (drift.totalIssues === 0) {
    return (
      <button id="drift-btn" className="clean" title="No config drift">
        &#x2713;
      </button>
    );
  }

  const goTo = (id: string) => {
    onGoTo(id);
    setOpen(false);
  };

  const cd = drift.constraintDrift;

  return (
    <>
      <button id="drift-btn" className="has-issues" onClick={() => setOpen((v) => !v)} title="Config drift detected">
        &#x26A0; {drift.totalIssues}
      </button>

      <div id="drift-panel" className={open ? 'open' : ''}>
        <div id="drift-header">
          <h2>Config Drift</h2>
          <button id="drift-close" onClick={() => setOpen(false)}>
            &times;
          </button>
        </div>

        {drift.unassignedTables.length > 0 && (
          <DriftSection title={`Unassigned Tables (${drift.unassignedTables.length})`} titleClass="amber" description="In database but not in any domain">
            {drift.unassignedTables.map((name) => (
              <div key={name} className="drift-item clickable" onClick={() => goTo(name)}>
                {name}
              </div>
            ))}
          </DriftSection>
        )}

        {drift.ghostTables.length > 0 && (
          <DriftSection title={`Ghost Tables (${drift.ghostTables.length})`} titleClass="red" description="In config but not in database">
            {drift.ghostTables.map((name) => (
              <div key={name} className="drift-item">
                {name}
              </div>
            ))}
          </DriftSection>
        )}

        {drift.unmappedFkColumns.length > 0 && (
          <DriftSection title={`Unmapped FK Columns (${drift.unmappedFkColumns.length})`} titleClass="blue" description="Look like FKs but have no mapping">
            {drift.unmappedFkColumns.map(({ table, column }) => (
              <div key={`${table}.${column}`} className="drift-item clickable" onClick={() => goTo(table)}>
                <span className="drift-table">{table}</span>.<span className="drift-col">{column}</span>
              </div>
            ))}
          </DriftSection>
        )}

        {drift.invalidFkTargets.length > 0 && (
          <DriftSection title={`Invalid FK Targets (${drift.invalidFkTargets.length})`} titleClass="red" description="FK mappings to non-existent tables">
            {drift.invalidFkTargets.map(({ column, target }) => (
              <div key={column} className="drift-item">
                {column} &rarr; <span className="drift-col">{target}</span>
              </div>
            ))}
          </DriftSection>
        )}

        {cd && cd.missingDbConstraints.length > 0 && (
          <DriftSection title={`Missing DB Constraints (${cd.missingDbConstraints.length})`} titleClass="amber" description="In config but no actual DB foreign key constraint">
            {cd.missingDbConstraints.map(({ table, column, target }) => (
              <div key={`${table}.${column}`} className="drift-item clickable" onClick={() => goTo(table)}>
                <span className="drift-table">{table}</span>.<span className="drift-col">{column}</span> &rarr; {target}
              </div>
            ))}
          </DriftSection>
        )}

        {cd && cd.extraDbConstraints.length > 0 && (
          <DriftSection title={`Extra DB Constraints (${cd.extraDbConstraints.length})`} titleClass="blue" description="DB has FK constraint but no config mapping">
            {cd.extraDbConstraints.map(({ table, column, referencedTable }) => (
              <div key={`${table}.${column}`} className="drift-item clickable" onClick={() => goTo(table)}>
                <span className="drift-table">{table}</span>.<span className="drift-col">{column}</span> &rarr; {referencedTable}
              </div>
            ))}
          </DriftSection>
        )}

        {cd && cd.mismatchedFkTargets.length > 0 && (
          <DriftSection title={`Mismatched FK Targets (${cd.mismatchedFkTargets.length})`} titleClass="red" description="Config and DB disagree on FK target table">
            {cd.mismatchedFkTargets.map(({ table, column, configTarget, actualTarget }) => (
              <div key={`${table}.${column}`} className="drift-item clickable" onClick={() => goTo(table)}>
                <span className="drift-table">{table}</span>.<span className="drift-col">{column}</span>: config &rarr; {configTarget}, DB &rarr; {actualTarget}
              </div>
            ))}
          </DriftSection>
        )}
      </div>
    </>
  );
}
