// projects/frontend/src/schema/components/TabBar.svelte
<script lang="ts">
  import { cx } from '../utils/utils';

  interface Props {
    tabs: { title: string }[];
    activeIndex: number;
    onselect: (index: number) => void;
  }
  let { tabs, activeIndex, onselect }: Props = $props();
</script>

<div id="tab-bar">
  {#each tabs as tab, i (i)}
    <button class={cx('tab-item', i === activeIndex && 'active')} onclick={() => onselect(i)}>
      {tab.title}
    </button>
  {/each}
</div>

// projects/frontend/src/schema/components/TabBar.tsx
import { cx } from '../utils/utils';

export function TabBar({ tabs, activeIndex, onSelect }: { tabs: { title: string }[]; activeIndex: number; onSelect: (index: number) => void }) {
  return (
    <div id="tab-bar">
      {tabs.map((tab, i) => (
        <button key={i} className={cx('tab-item', i === activeIndex && 'active')} onClick={() => onSelect(i)}>
          {tab.title}
        </button>
      ))}
    </div>
  );
}
