// projects/frontend/src/schema/components/Toolbar.svelte
<script lang="ts">
  import { cx } from '../utils/utils';
  import ThemeSwitcher from './ThemeSwitcher.svelte';
  import type { Palette, Mode } from '../hooks/useTheme.svelte';

  interface Props {
    title: string;
    tableCount: number;
    fkCount: number;
    searchQuery: string;
    onsearchchange: (query: string) => void;
    legendItems: LegendItem[];
    activeDomains: Set<string>;
    ontoggledomain: (keys: string[]) => void;
    palette: Palette;
    themeMode: Mode;
    onpalettechange: (p: Palette) => void;
    ontogglemode: () => void;
    viewMode: string;
    onviewmodechange: (m: 'browse' | 'canvas') => void;
  }
  let {
    title, tableCount, fkCount, searchQuery, onsearchchange,
    legendItems, activeDomains, ontoggledomain,
    palette, themeMode, onpalettechange, ontogglemode,
    viewMode, onviewmodechange,
  }: Props = $props();
</script>

<div id="toolbar">
  <h1>{title}</h1>
  <span class="stats">{tableCount} tables &middot; {fkCount} relations</span>
  <input
    type="text"
    id="search"
    placeholder="Search tables, columns..."
    value={searchQuery}
    oninput={(e) => onsearchchange((e.target as HTMLInputElement).value)}
  />
  <div class="legend">
    {#each legendItems as item (item.key)}
      <div
        class={cx('legend-item', !item.groupKeys.some((k) => activeDomains.has(k)) && 'dimmed')}
        onclick={() => ontoggledomain(item.groupKeys)}
        role="button"
        tabindex="0"
        onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') ontoggledomain(item.groupKeys); }}
      >
        <div class="legend-dot" style="background: {item.color}"></div>
        {item.label}
      </div>
    {/each}
  </div>
  <div class="schema-mode-toggle">
    <button
      class={cx('mode-btn', viewMode === 'browse' && 'active')}
      onclick={() => onviewmodechange('browse')}
      title="Browse tables"
    >☰</button>
    <button
      class={cx('mode-btn', viewMode === 'canvas' && 'active')}
      onclick={() => onviewmodechange('canvas')}
      title="Canvas view"
    >⊞</button>
  </div>
  <ThemeSwitcher {palette} mode={themeMode} {onpalettechange} {ontogglemode} />
</div>

// projects/frontend/src/schema/components/Toolbar.tsx
import { cx } from '../utils/utils';
import { ThemeSwitcher } from './ThemeSwitcher';
import type { Palette, Mode } from '../hooks/useTheme';

export function Toolbar({
  title,
  tableCount,
  fkCount,
  searchQuery,
  onSearchChange,
  legendItems,
  activeDomains,
  onToggleDomain,
  palette,
  themeMode,
  onPaletteChange,
  onToggleMode,
  viewMode,
  onViewModeChange,
}: {
  title: string;
  tableCount: number;
  fkCount: number;
  searchQuery: string;
  onSearchChange: (query: string) => void;
  legendItems: LegendItem[];
  activeDomains: Set<string>;
  onToggleDomain: (keys: string[]) => void;
  palette: Palette;
  themeMode: Mode;
  onPaletteChange: (p: Palette) => void;
  onToggleMode: () => void;
  viewMode: string;
  onViewModeChange: (m: 'browse' | 'canvas') => void;
}) {
  return (
    <div id="toolbar">
      <h1>{title}</h1>
      <span className="stats">
        {tableCount} tables &middot; {fkCount} relations
      </span>
      <input
        type="text" id="search" placeholder="Search tables, columns..."
        value={searchQuery}
        onInput={(e) => onSearchChange((e.target as HTMLInputElement).value)}
      />
      <div className="legend">
        {legendItems.map((item) => (
          <div
            key={item.key}
            className={cx('legend-item', !item.groupKeys.some((k) => activeDomains.has(k)) && 'dimmed')}
            onClick={() => onToggleDomain(item.groupKeys)}
          >
            <div className="legend-dot" style={{ background: item.color }} />
            {item.label}
          </div>
        ))}
      </div>
      <div className="schema-mode-toggle">
        <button
          className={cx('mode-btn', viewMode === 'browse' && 'active')}
          onClick={() => onViewModeChange('browse')}
          title="Browse tables"
        >☰</button>
        <button
          className={cx('mode-btn', viewMode === 'canvas' && 'active')}
          onClick={() => onViewModeChange('canvas')}
          title="Canvas view"
        >⊞</button>
      </div>
      <ThemeSwitcher palette={palette} mode={themeMode} onPaletteChange={onPaletteChange} onToggleMode={onToggleMode} />
    </div>
  );
}
