// projects/frontend/src/schema/components/ZoomControls.tsx
export function ZoomControls({ onZoomIn, onZoomOut, onFitAll }: { onZoomIn: () => void; onZoomOut: () => void; onFitAll: () => void }) {
  return (
    <div id="zoom-controls">
      <button title="Zoom in" onClick={onZoomIn}>
        +
      </button>
      <button title="Zoom out" onClick={onZoomOut}>
        &minus;
      </button>
      <button title="Fit all" onClick={onFitAll}>
        &#x25A3;
      </button>
    </div>
  );
}

// projects/frontend/src/schema/components/ZoomControls.svelte
<script lang="ts">
  interface Props {
    onzoomin: () => void;
    onzoomout: () => void;
    onfitall: () => void;
  }
  let { onzoomin, onzoomout, onfitall }: Props = $props();
</script>

<div id="zoom-controls">
  <button title="Zoom in" onclick={onzoomin}>+</button>
  <button title="Zoom out" onclick={onzoomout}>&minus;</button>
  <button title="Fit all" onclick={onfitall}>&#x25A3;</button>
</div>
